### ISSUE TITLE
server_name.bce

### ISSUE THREAD

**Issue by wrllinwr** [uglyoldbob/l1j-client#13]
What about content of server_name.bce file. Does it be wrote automatically by Client? And the client how to update from Analyzer server.

**Comment by uglyoldbob** [comment]
The bce file should be created and handled by the client.

**Comment by wrllinwr** [comment]
I was in the confusion Port and GamePort, it led to didn't created ServerName.bce file. Port=2003, it's the updates process.
But I haven't success connect to the GameServer now. Java Server always created new Thread till out of memory.

It seems stop at first InputStream.read() of both 
ClientServer.readPacket() {int hiByte = _from_client.read();} and 
ServerClient.readPacket(){int hiByte = _from_server.read();}

It's strange that the java not throw any Exception.
