### ISSUE TITLE
Mavericks Support

### ISSUE THREAD

**Issue by scottbasgaard** [uglyoldbob/l1j-client#6]
@uglyoldbob Just stumbled upon this project and wondering if you've got the client working on Mavericks?

**Comment by uglyoldbob** [comment]
I dont have a system with mavericks to do testing with. Im just guessing that it will work just fine though since it is on a 64 bit x86 cpu.

**Comment by scottbasgaard** [comment]
@uglyoldbob yea should be :+1:

Don't want to flood your GitHub issues with support questions so if there's a better place to contact you let me know.

I'm wondering if you can help me with:

>configure: "Building on mac"
>checking for Mix_Init in -framework SDL_mixer... no
>configure: error: "SDL_mixer framework not found"

When I run `$ ../compile` from /src/

**Comment by uglyoldbob** [comment]
You will need to install the frameworks for the project.
https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/InstallingFrameworks.html
The frameworks required are:
SDL_mixer (https://www.libsdl.org/projects/SDL_mixer/release-1.2.html) (https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.dmg)
SDL_image (https://www.libsdl.org/projects/SDL_image/release-1.2.html) (https://www.libsdl.org/projects/SDL_image/release/SDL_image-1.2.12.dmg)
SDL (https://www.libsdl.org/download-1.2.php) (https://www.libsdl.org/release/SDL-1.2.15.dmg)

**Comment by scottbasgaard** [comment]
@uglyoldbob perfect, on it, thanks!

**Comment by scottbasgaard** [comment]
Gave up on this :disappointed: one day!
