### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by scottbasgaard** [uglyoldbob/l1j-client#8]
Anything still going on here?

**Comment by uglyoldbob** [comment]
I'm not currently developing this project, but may work on it in the future.

**Comment by scottbasgaard** [comment]
Will stay tuned!

**Comment by uglyoldbob** [comment]
Started developing the client in rust.

**Comment by scottbasgaard** [comment]
@uglyoldbob wow really! Any way I can follow along / help?

**Comment by scottbasgaard** [comment]
Found it ;) https://github.com/uglyoldbob/rustlin-server

**Comment by uglyoldbob** [comment]
Check out my rustlin-server repository where development is happening in
rust. It has a goal of implementing both game client and server.
